name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  java_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: github

      - name: Build with Gradle
        run: ./gradlew clean build
